### ISSUE TITLE
Create Home Page

### ISSUE THREAD

**Issue by garrett-manley** [sam-breaux/Project-Resource-Manager#4]
Showcases projects in chronological order

## TODO

- [ ] Create Android View
- [ ] Create iOS View
- [ ] Create "Home" ViewModel
- [ ] Create "Project" model

### Project

```json
{
  "title": "string",
  "imageUrl": "string",
  "description": "string"
}
```

### Home ViewModel

```json
{
  "projects": []
}
```

## Acceptance Criteria

Given a user is launches the app
When they land on the homepage
Then display a list of project "Cards"
